<?xml version="1.0" encoding="UTF-8"?><testrun name="RealtimeWeatherRepositoryTests.testFindByTrashedLocationNotFound" project="WeatherApiService" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="com.weatherapi.weatherforecast.realtime.RealtimeWeatherRepositoryTests" time="0.971" displayname="RealtimeWeatherRepositoryTests" uniqueid="[engine:junit-jupiter]/[class:com.weatherapi.weatherforecast.realtime.RealtimeWeatherRepositoryTests]">
    <testcase name="testFindByTrashedLocationNotFound" classname="com.weatherapi.weatherforecast.realtime.RealtimeWeatherRepositoryTests" time="0.971" displayname="testFindByTrashedLocationNotFound()" uniqueid="[engine:junit-jupiter]/[class:com.weatherapi.weatherforecast.realtime.RealtimeWeatherRepositoryTests]/[method:testFindByTrashedLocationNotFound()]">
      <failure>
        <expected>null</expected>
        <actual>com.weatherapi.weatherforecast.common.RealtimeWeather@10395bc4</actual>
        org.opentest4j.AssertionFailedError: &#13;
expected: null&#13;
 but was: com.weatherapi.weatherforecast.common.RealtimeWeather@10395bc4&#13;
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)&#13;
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)&#13;
	at com.weatherapi.weatherforecast.realtime.RealtimeWeatherRepositoryTests.testFindByTrashedLocationNotFound(RealtimeWeatherRepositoryTests.java:94)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;

      </failure>
    </testcase>
  </testsuite>
</testrun>
